name: dl-minicourse
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - jupyterlab
  - pytorch>=1.4
  - torchvision>=0.5
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - pip:
    - torchviz
