name: NYU-DL
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - jupyterlab
  - pytorch
  - torchvision
  - torchtext
  - opencv
  - librosa
  - ipympl
  - pip:
    - torchviz
