name: Translation Updates
on:
  workflow_dispatch:
  push:
     paths:
       - "*.md"
jobs:
  push:
    name: Translation Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Translation Updates
        uses: rrajj/gha-checklist-badges@main
        with:
          readme-fname: README.md
          nfr-fnames: langs-update/hu.md langs-update/sr.md langs-update/ja.md langs-update/tr.md langs-update/en.md langs-update/ru.md langs-update/zh.md langs-update/bn.md langs-update/it.md langs-update/fr.md langs-update/vi.md langs-update/fa.md langs-update/ko.md langs-update/ar.md langs-update/pt.md langs-update/es.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
